### PR TITLE
Define target definition for all targets.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by xwu-intel** [comment]
Are you adding arrow lib dependencies for C++ ? As I understand, there is no need as we follow Arrow C data interface?

 Could not find a package configuration file provided by "Arrow" with any of
  the following names:

    ArrowConfig.cmake
    arrow-config.cmake

**Comment by trivialfis** [comment]
> As I understand, there is no need as we follow Arrow C data interface?

That's interesting.  Thanks for sharing.

**Comment by trivialfis** [comment]
Removed the packaging linking part.

**Comment by trivialfis** [comment]
Since this doesn't add any direct C dependency, I think the `USE_ARROW` might be removed entirely.

**Comment by xwu-intel** [comment]
> Since this doesn't add any direct C dependency, I think the `USE_ARROW` might be removed entirely.

If you want built-in arrow support we can remove USE_ARROW. Alternatively we can set USE_ARROW as ON by default if you like.

**Pull request closed without merging**
